gnzlbg/jemallocator

.travis.yml
Rustup can be used to add additional target directly now.
=> travis: fix broken target installation

.travis.yml, src/lib.rs
This pr tries to expose a more convenient interface for mallctl. Two methods are still marked as unsafe because the generic type T may not be the exact type what caller wants. For example, if user pass `&str` to `mallctl_set`, it will apparently cause inappropriate memory manipulation.
=> make mallctl more simple

src/lib.rs
rust-lang/rust#40409 requires a __rust_alloc_zeroed function.
=> Fix test failure

systest/Cargo.toml
The build and tests pass on ppc64le after the change, more details in https://github.com/alexcrichton/jemallocator/issues/12
=> Upgrade libc dependency in systest to extend support to ppc64le

Cargo.toml, jemalloc-sys/Cargo.toml, jemalloc-sys/src/lib.rs, src/lib.rs, tests/smoke_ffi.rs
That is, those documented in http://jemalloc.net/jemalloc.3.html
For example `malloc` and `free` can be useful when implementing callbacks for a C library that doesn’t provide a size when deallocating: https://www.freetype.org/freetype2/docs/reference/ft2-system_interface.html
=> Add bindings to all jemalloc public functions

src/lib.rs, tests/smoke.rs
Same as https://github.com/rust-lang/rust/pull/46117
See also discussion of jemalloc’s behavior at https://github.com/jemalloc/jemalloc/issues/1072
=> Don’t assume MIN_ALIGN for small sizes

src/lib.rs
If this changes the `alloc_excess` benchmark in #26, then the `usable_size` might not be inlined properly, resulting in the `align_to_flags` function being executed twice.
=> Add alloc_excess/realloc_excess

src/lib.rs
- Also rename `align_to_flags(align, size)` to
`layout_to_flags(layout)` because it was taking
its parameters in a weird order (typically its
size first and align second) and size + align
is actually just `Layout`.
=> [bugfix] update align to flags in excess methods

jemalloc-sys/Cargo.toml
Updates jemalloc to rust-lang/jemalloc branch: rust-2017-10-09
=> Update jemalloc to 5.0.1

jemalloc-sys/build.rs
The PR #34 was merged with a broken `i686-apple-darwin` build. This PR fixes that.
=> [bugfix] jemalloc i686-apple-darwin build

Cargo.toml, src/lib.rs, tests/malloctl.rs, tests/smoke.rs
CC https://github.com/rust-lang/rust/pull/49669
=> Implement the GlobalAlloc trait, upgrade to nightly-2018-04-15

Cargo.toml, src/lib.rs
https://github.com/rust-lang/rust/pull/50144 removed `oom` trait methods.
=>  Upgrade to rustc 1.27.0-nightly (7f3444e1b 2018-04-26) 

Cargo.toml, jemalloc-sys/build.rs
background threads were previously always disabled since cargo upper
cases feature names. jemallocator also enabled default features on
jemalloc-sys.
=> Fix bg_thread feature

jemalloc-sys/build.rs
They otherwise conflict with the same symbols pulled in via the jemalloc
rustc provides if a custom global allocator isn't set.
Closes #51
=> Set a custom prefix for jemalloc internal symbols

jemalloc-sys/build.rs
The point of the `no_prefix` flag it to override libc symbols like `malloc`, it shouldn’t affect jemalloc’s internal APIs.
Fixes https://github.com/alexcrichton/jemallocator/pull/53#issuecomment-399782316.
=> Prefix private symbols unconditionally

ci/run.sh
This PR temporarily works around a toolchain bug.
=> Temporarily workaround around toolchain bug

src/lib.rs
This PR fixes a bug in the `shrink_in_place` implementation: if the size of the shrunk memory block is greater or equal than the desired size it currently errors, but this should actually be a success, and the else branch cannot ever happen unless there is a bug in jemalloc.
That is, the user asks for a desired size that is smaller than the original allocation size, and we are allowed to return a memory block that is larger than that.
=> fix shrink_in_place implementation

jemalloc-sys/src/lib.rs, jemalloc-sys/tests/malloc_conf_empty.rs, jemalloc-sys/tests/malloc_conf_set.rs, systest/Cargo.toml
`malloc_conf` is useful for setting configuration options at compile-time, like `background_thread:true`.
=> Expose malloc_conf

Cargo.toml, jemalloc-sys/Cargo.toml, jemalloc-sys/src/lib.rs, jemalloc-sys/tests/malloc_conf_set.rs, systest/Cargo.toml, tests/ffi.rs
It turns out that `malloc_message` is null by default, so it has to be updated to an `Option<fn>`. That's an API breaking change, so i'm updating `malloc_stats_print` here as well (#22). 
The background thread feature renames are going to be backwards incompatible as well, so I'll wait for those to do a new release.  I'm bumping the version to 0.2 (as agreed in #22) so that we don't accidentally make a backwards incompatible 0.1 release.
=> Make some function pointers nullable and test writing to malloc_conf

.travis.yml, Cargo.toml, ci/run.sh, jemalloc-sys/Cargo.toml, jemalloc-sys/build.rs, jemalloc-sys/readme.md, src/lib.rs, tests/background_thread_defaults.rs, tests/background_thread_enabled.rs
* rename `bg_thread` feature to `background_threads_runtime_support`
* add `background_threads` option to enable background threads at run-time
* [breaking change]: use a newtype for `mallctl` errors
* warn if unprefixed jemalloc requested in an unsupported platform
=> Background threads

.travis.yml, Cargo.toml, jemalloc-sys/Cargo.toml, jemalloc-sys/src/lib.rs
The fields of the `extent_hooks_s` type were `*mut fn(...)->...`  which are pointers to function pointers, but they should have been function pointers (`Option<fn(...)->...>`) instead. 
`ctest` does not see through type aliases, and needs to know from syntax whether the type inside an `Option` is a `fn` or not to be able to generate the appropriate tests, so this PR duplicates the struct for documentation purposes behind a `--cfg jemallocator_docs` flag, so that the type aliases are properly rendered in the docs. To avoid breaking `docs.rs` we include this in the cargo meta-data.
=> Fix extent hooks struct

.travis.yml, Cargo.toml, ci/run.sh, jemalloc-sys/Cargo.toml
`libc` is pulling `libstd` because we are enabling the `use_std` libc feature (it's enabled by default). This PR changes that by depending on `libc` without `use_std`, and verifies that the `emallocator` and `jemalloc-sys` rlibs do not contain std symbols using `nm`.
=> Make jemallocator not contain std symbols by default

src/lib.rs, tests/shrink_in_place.rs
The current `shrink_in_place` implementation is incorrect. It returns `Ok` if the `usable_size` returned by `xmallocx` is `>= new_size`. 
However, `xmallocx` returns the `usable_size` of the original allocation, which is `>= new_size`, if: 
* the allocation cannot be shrunk in place, e.g., because  `new_size` lands in a different size-class -  we must return error here since `new_size` cannot be used to deallocate the allocation but `Alloc::shrink_in_place` users are allowed to do that on success
* `new_size` is in the same size-class as the original allocation - in which the allocation was shrunk appropriately by zero, and `new_size` can be used to deallocate the allocation since it lands in the same size-class
=> Fix shrink_in_place

Cargo.toml, ci/run.sh, jemalloc-sys/Cargo.toml, jemalloc-sys/readme.md, jemallocator-global/Cargo.toml, jemallocator-global/LICENSE-APACHE, jemallocator-global/LICENSE-MIT, jemallocator-global/README.md, jemallocator-global/src/lib.rs
This adds a `jemallocator-global` crate that sets `jemallocator` as the `#[global_allocator]` in those platforms in which it is supported and does nothing otherwise. It also comes with a `force` cargo feature that unconditionally sets it as the global allocator. 
It currently does not "conditionally" export any of the `jemallocator` features - I don't know whether doing this is even possible, but those who need more control should just use `jemallocator` directly, it's ok for this library to just be a convenience that gives you `jemallocator` with its default features enabled.
cc @sfackler
=> Add jemallocator-global crate

Cargo.toml, jemalloc-sys/Cargo.toml, jemalloc-sys/README.md, jemalloc-sys/build.rs
This feature allows libraries that link against jemalloc to be dlopened. This is useful when you want to e.g. build Python modules using PyO3 that still leverage the superior performance of jemalloc.
See
https://github.com/jemalloc/jemalloc/issues/937
https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md
for a detailed explanation of the feature.
=> Add disable_initial_exec_tls feature

jemalloc-ctl/src/error.rs
Only when "use_std". Extracts the string descriptions to share between Debug, Display, and StdError.
=> jemalloc-ctl: impl std::error::Error for Error

README.md
Pretty straightforward - fix the link to the README.md file
=> Fix link to jemallocator-sys' README.md file

src/lib.rs
This is why the CI for jemallocator is failing right now.
**Edit:** Or at least, it's why the build for the actual `jemallocator` crate fails in a context where you're using `JEMALLOC_OVERRIDE`, and **not** building `jemalloc` itself.
=> Fix wrong spelling of `unreachable unchecked`.

README.md
Added usage instructions for current Rust, and added measures to prevent from being used on `msvc` targets.
=> Added updated usage instructions

jemalloc-sys/build.rs
1. Adapt android toolchain names
2. Use correct symbol prefix when using prebuilt jemalloc
=> build.rs enhancements
